### ISSUE TITLE
Catena 4801 simple sketch broke with latest Modbus library

### ISSUE THREAD

**Issue by dhineshkumarmcci** [mcci-catena/Catena-Sketches#107]
The catena4801_simple sketch has to be updated in a similar way to work with latest Modbus library release.

**Comment by terrillmoore** [comment]
Yes, or I need to fix the library. It would be better to fix the library. It is not difficult; need to change the inner class name to something distinct.

**Comment by dhineshkumarmcci** [comment]
Hopefully, we can fix it in the sketch. We were able to compile the sketch with minor changes.
