### ISSUE TITLE
Lux Sensor not working with Catena4551_test01 Sketch

### ISSUE THREAD

**Issue by svelmurugan92** [mcci-catena/Catena-Sketches#36]
Tested the Catena4551_test01 Sketch, Lux sensor output is not coming.

**Comment by svelmurugan92** [comment]
While initialize the Lux sensor, wrong flag used. 
In line no: 262, Added the correct flag fHasLuxSi1133, 
Now we can see Lux sensor output

**Comment by terrillmoore** [comment]
Please use permalinks to the line number, like this: https://github.com/mcci-catena/Catena-Sketches/blob/b67901b11caae3e4ab95e7c63d708579c26df0f4/catena4551_test01/catena4551_test01.ino#L262

You can easily get this by clicking on the line number in the code view, getting a `...`, then clicking again for a menu, and selecting "copy permalink".
