### ISSUE TITLE
Water Depth Sensor

### ISSUE THREAD

**Issue by NickWaterton** [mcci-catena/Catena-Sketches#42]
In the catena4450m102_waterlevel sketch, you refer to an RC601 water pressure transducer, which uses an I2C interface.

Do you have a link to this device, or a datasheet? I can't find a reference to it anywhere on the web.
I am using this [bluerobotics bar02 sensor](https://www.bluerobotics.com/store/electronics/bar02-sensor-r1-rp) but it's quite expensive (although it is super accurate, and low power).

Always looking for alternatives!

**Comment by terrillmoore** [comment]
We get it from a vendor in China. I wasn't involved in the procurement, but I think @svelmurugan92 can post a reference here.

**Comment by svelmurugan92** [comment]
Hello Nick,

We used Dalian Rayco's RC600 series water pressure transducer. Special version RC606 has I2C interface.
https://rayco20150306.en.ec21.com/RC600_Liquid_Level_Transmitter--9414097_9438509.html 

You need to contact Rayco for special requirements, Cable length, Output interface type etc..

FYR, Below is the photo of sensor

![rayco_sensor_3](https://user-images.githubusercontent.com/16336054/44183816-2a966d80-a12a-11e8-86be-400d355f160d.jpeg)

![rayco-rc606](https://user-images.githubusercontent.com/16336054/44183822-2e29f480-a12a-11e8-8044-411f829718dd.jpg)

Thank you!

Best Regards,
Velmurugan S
